package enums;

public class Enums {

    public enum HeaderType {
        APP_HEADER_LOG_IN_PAGE,
        LOGIN_HEADER_LOG_IN_PAGE,
        SIGNUP_HEADER_LOG_IN_PAGE,
        ERROR_HEADER_LOG_IN_PAGE,
        ADD_USER_HEADER_SIGN_UP_PAGE,
        SIGNUP_HEADER_SIGN_UP_PAGE,
        CONTACT_LIST_HEADER_CONTACT_LIST_PAGE,
        INFO_HEADER_CONTACT_LIST_PAGE,
        ADD_CONTACT_HEADER_ADD_CONTACT_PAGE,
        REQUIRED_FIELD_ERROR_ADD_CONTACT_PAGE,
        CONTACT_DETAILS_HEADER_CONTACT_DETAILS_PAGE
    }

    public enum ButtonType {
        SUBMIT_BUTTON_LOG_IN_PAGE,
        SIGNUP_BUTTON_LOG_IN_PAGE,
        SUBMIT_BUTTON_SIGN_UP_PAGE,
        CANCEL_BUTTON_SIGN_UP_PAGE,
        ADD_CONTACT_BUTTON_CONTACT_LIST_PAGE,
        LOGOUT_BUTTON_CONTACT_LIST_PAGE,
        SUBMIT_BUTTON_ADD_CONTACT_PAGE,
        CANCEL_BUTTON_ADD_CONTACT_PAGE,
        LOGOUT_BUTTON_ADD_CONTACT_PAGE,
        EDIT_CONTACT_BUTTON_CONTACT_DETAILS_PAGE,
        DELETE_BUTTON_CONTACT_DETAILS_PAGE,
        RETURN_BUTTON_CONTACT_DETAILS_PAGE,
        LOGOUT_BUTTON_CONTACT_DETAILS_PAGE
    }
}
